rule win_dripion_auto {

    meta:
        id = "13hsUSFX0guBJexVMXwrJD"
        fingerprint = "v1_sha256_b54fd3ad608c7c63f9361c36ed20fa92f663e8b7a12233b0f074e7ff124b365a"
        version = "1"
        date = "2024-10-31"
        modified = "2025-04-03"
        status = "RELEASED"
        sharing = "TLP:WHITE"
        source = "YARA-RULES-COLLECTION"
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        description = "Detects win.dripion."
        category = "INFO"
        info = "AUTOGENERATED RULE BROUGHT TO YOU BY YARA-SIGNATOR"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dripion"
        malpedia_rule_date = "20241030"
        malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
        malpedia_version = "20241030"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    strings:
        $sequence_0 = { ffd6 03f8 7402 ffd6 }
            // n = 4, score = 400
            //   ffd6                 | call                esi
            //   03f8                 | add                 edi, eax
            //   7402                 | je                  4
            //   ffd6                 | call                esi

        $sequence_1 = { 03f8 7402 ffd6 ffd6 ffd6 }
            // n = 5, score = 400
            //   03f8                 | add                 edi, eax
            //   7402                 | je                  4
            //   ffd6                 | call                esi
            //   ffd6                 | call                esi
            //   ffd6                 | call                esi

        $sequence_2 = { 03f8 ffd6 8bd8 ffd6 0fafd8 }
            // n = 5, score = 400
            //   03f8                 | add                 edi, eax
            //   ffd6                 | call                esi
            //   8bd8                 | mov                 ebx, eax
            //   ffd6                 | call                esi
            //   0fafd8               | imul                ebx, eax

        $sequence_3 = { ffd6 03f8 ffd6 8bd8 ffd6 0fafd8 ffd6 }
            // n = 7, score = 400
            //   ffd6                 | call                esi
            //   03f8                 | add                 edi, eax
            //   ffd6                 | call                esi
            //   8bd8                 | mov                 ebx, eax
            //   ffd6                 | call                esi
            //   0fafd8               | imul                ebx, eax
            //   ffd6                 | call                esi

        $sequence_4 = { 740f 3ccf 740b 34cf }
            // n = 4, score = 400
            //   740f                 | je                  0x11
            //   3ccf                 | cmp                 al, 0xcf
            //   740b                 | je                  0xd
            //   34cf                 | xor                 al, 0xcf

        $sequence_5 = { ffd6 03f8 ffd6 8bd8 ffd6 0fafd8 }
            // n = 6, score = 400
            //   ffd6                 | call                esi
            //   03f8                 | add                 edi, eax
            //   ffd6                 | call                esi
            //   8bd8                 | mov                 ebx, eax
            //   ffd6                 | call                esi
            //   0fafd8               | imul                ebx, eax

        $sequence_6 = { 7513 6a64 ff15???????? 68???????? }
            // n = 4, score = 400
            //   7513                 | jne                 0x15
            //   6a64                 | push                0x64
            //   ff15????????         |                     
            //   68????????           |                     

        $sequence_7 = { 8bf8 ffd6 0faff8 8d3c7f }
            // n = 4, score = 400
            //   8bf8                 | mov                 edi, eax
            //   ffd6                 | call                esi
            //   0faff8               | imul                edi, eax
            //   8d3c7f               | lea                 edi, [edi + edi*2]

        $sequence_8 = { ffd6 03f8 7402 ffd6 ffd6 }
            // n = 5, score = 400
            //   ffd6                 | call                esi
            //   03f8                 | add                 edi, eax
            //   7402                 | je                  4
            //   ffd6                 | call                esi
            //   ffd6                 | call                esi

        $sequence_9 = { 8bf8 ffd6 0faff8 ffd6 }
            // n = 4, score = 400
            //   8bf8                 | mov                 edi, eax
            //   ffd6                 | call                esi
            //   0faff8               | imul                edi, eax
            //   ffd6                 | call                esi

    condition:
        7 of them and filesize < 90112
}
