rule win_wonknu_auto {

    meta:
        id = "7BmP1WRrPtAbUJMw5oh3fj"
        fingerprint = "v1_sha256_d8729848e6f29de29baa83d3d1b7a400fd076f81fa4553c7cf2ef20e4ee0bd77"
        version = "1"
        date = "2024-10-31"
        modified = "2025-02-27"
        status = "RELEASED"
        sharing = "TLP:WHITE"
        source = "MALPEDIA"
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        description = "Detects win.wonknu."
        category = "INFO"
        info = "AUTOGENERATED RULE BROUGHT TO YOU BY YARA-SIGNATOR"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.wonknu"
        malpedia_rule_date = "20241030"
        malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
        malpedia_version = "20241030"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    strings:
        $sequence_0 = { e8???????? 8bfc b901050000 f3a5 8bcb e8???????? 803b00 }
            // n = 7, score = 200
            //   e8????????           |                     
            //   8bfc                 | mov                 edi, esp
            //   b901050000           | mov                 ecx, 0x501
            //   f3a5                 | rep movsd           dword ptr es:[edi], dword ptr [esi]
            //   8bcb                 | mov                 ecx, ebx
            //   e8????????           |                     
            //   803b00               | cmp                 byte ptr [ebx], 0

        $sequence_1 = { eb08 c6840550ffffff00 8d8550ffffff 50 e8???????? }
            // n = 5, score = 200
            //   eb08                 | jmp                 0xa
            //   c6840550ffffff00     | mov                 byte ptr [ebp + eax - 0xb0], 0
            //   8d8550ffffff         | lea                 eax, [ebp - 0xb0]
            //   50                   | push                eax
            //   e8????????           |                     

        $sequence_2 = { 8bfc b901050000 f3a5 8bcb e8???????? 803b00 }
            // n = 6, score = 200
            //   8bfc                 | mov                 edi, esp
            //   b901050000           | mov                 ecx, 0x501
            //   f3a5                 | rep movsd           dword ptr es:[edi], dword ptr [esi]
            //   8bcb                 | mov                 ecx, ebx
            //   e8????????           |                     
            //   803b00               | cmp                 byte ptr [ebx], 0

        $sequence_3 = { 8d7e28 57 ff15???????? 8b4608 }
            // n = 4, score = 200
            //   8d7e28               | lea                 edi, [esi + 0x28]
            //   57                   | push                edi
            //   ff15????????         |                     
            //   8b4608               | mov                 eax, dword ptr [esi + 8]

        $sequence_4 = { e8???????? 8bfc b901050000 f3a5 8bcb }
            // n = 5, score = 200
            //   e8????????           |                     
            //   8bfc                 | mov                 edi, esp
            //   b901050000           | mov                 ecx, 0x501
            //   f3a5                 | rep movsd           dword ptr es:[edi], dword ptr [esi]
            //   8bcb                 | mov                 ecx, ebx

        $sequence_5 = { f3a5 8bcb e8???????? 803b00 }
            // n = 4, score = 200
            //   f3a5                 | rep movsd           dword ptr es:[edi], dword ptr [esi]
            //   8bcb                 | mov                 ecx, ebx
            //   e8????????           |                     
            //   803b00               | cmp                 byte ptr [ebx], 0

        $sequence_6 = { 8bfc b901050000 f3a5 8bcb }
            // n = 4, score = 200
            //   8bfc                 | mov                 edi, esp
            //   b901050000           | mov                 ecx, 0x501
            //   f3a5                 | rep movsd           dword ptr es:[edi], dword ptr [esi]
            //   8bcb                 | mov                 ecx, ebx

        $sequence_7 = { c6840550ffffff00 8d8550ffffff 50 e8???????? }
            // n = 4, score = 200
            //   c6840550ffffff00     | mov                 byte ptr [ebp + eax - 0xb0], 0
            //   8d8550ffffff         | lea                 eax, [ebp - 0xb0]
            //   50                   | push                eax
            //   e8????????           |                     

        $sequence_8 = { 53 56 57 6804140000 }
            // n = 4, score = 200
            //   53                   | push                ebx
            //   56                   | push                esi
            //   57                   | push                edi
            //   6804140000           | push                0x1404

        $sequence_9 = { e8???????? 8bfc b901050000 f3a5 8bcb e8???????? }
            // n = 6, score = 200
            //   e8????????           |                     
            //   8bfc                 | mov                 edi, esp
            //   b901050000           | mov                 ecx, 0x501
            //   f3a5                 | rep movsd           dword ptr es:[edi], dword ptr [esi]
            //   8bcb                 | mov                 ecx, ebx
            //   e8????????           |                     

    condition:
        7 of them and filesize < 540672
}
