rule win_dropshot_auto {

    meta:
        id = "5faEb2ZtK9ufBmVClCtpWU"
        fingerprint = "v1_sha256_3f5f25fe800a01f710cc89be583f98653a26f14448d6ba599306a1d4d7c2a368"
        version = "1"
        date = "2024-10-31"
        modified = "2025-02-27"
        status = "RELEASED"
        sharing = "TLP:WHITE"
        source = "MALPEDIA"
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        description = "Detects win.dropshot."
        category = "INFO"
        info = "AUTOGENERATED RULE BROUGHT TO YOU BY YARA-SIGNATOR"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dropshot"
        malpedia_rule_date = "20241030"
        malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
        malpedia_version = "20241030"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    strings:
        $sequence_0 = { ff15???????? 5d c3 3b0d???????? f27502 f2c3 }
            // n = 6, score = 200
            //   ff15????????         |                     
            //   5d                   | pop                 ebp
            //   c3                   | ret                 
            //   3b0d????????         |                     
            //   f27502               | bnd jne             5
            //   f2c3                 | bnd ret             

        $sequence_1 = { e8???????? 83c40c 6a04 6800100000 6804010000 6a00 ff15???????? }
            // n = 7, score = 200
            //   e8????????           |                     
            //   83c40c               | add                 esp, 0xc
            //   6a04                 | push                4
            //   6800100000           | push                0x1000
            //   6804010000           | push                0x104
            //   6a00                 | push                0
            //   ff15????????         |                     

        $sequence_2 = { 6a64 ff15???????? 6800800000 6a00 }
            // n = 4, score = 200
            //   6a64                 | push                0x64
            //   ff15????????         |                     
            //   6800800000           | push                0x8000
            //   6a00                 | push                0

        $sequence_3 = { ff15???????? 6a04 6800100000 6808020000 6a00 }
            // n = 5, score = 200
            //   ff15????????         |                     
            //   6a04                 | push                4
            //   6800100000           | push                0x1000
            //   6808020000           | push                0x208
            //   6a00                 | push                0

        $sequence_4 = { eb05 e8???????? 68e8030000 ff15???????? }
            // n = 4, score = 200
            //   eb05                 | jmp                 7
            //   e8????????           |                     
            //   68e8030000           | push                0x3e8
            //   ff15????????         |                     

        $sequence_5 = { 6a00 68???????? 6a00 ff15???????? b801000000 }
            // n = 5, score = 200
            //   6a00                 | push                0
            //   68????????           |                     
            //   6a00                 | push                0
            //   ff15????????         |                     
            //   b801000000           | mov                 eax, 1

        $sequence_6 = { 6a00 ff15???????? 6a05 ff15???????? ff15???????? }
            // n = 5, score = 200
            //   6a00                 | push                0
            //   ff15????????         |                     
            //   6a05                 | push                5
            //   ff15????????         |                     
            //   ff15????????         |                     

        $sequence_7 = { 6a00 6a00 ff15???????? 6a00 6a00 68???????? }
            // n = 6, score = 200
            //   6a00                 | push                0
            //   6a00                 | push                0
            //   ff15????????         |                     
            //   6a00                 | push                0
            //   6a00                 | push                0
            //   68????????           |                     

    condition:
        7 of them and filesize < 483328
}
